# Generated by Django 4.2.7 on 2023-12-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
